### PR TITLE
Rename function vars for global clang-tidy checks

### PR DESCRIPTION
**Pull request by sv99**
Massive internal vars and function rename in the Raiser and X86 subsystem for satisfy global .clang-tidy configuration.

### CODE REVIEW

**Comment by sv99** [comment]
I have some additional PR.
1. Rename internal vars in the arm subsystem
2. Add pretty printer for MachineFunction dumper - show registers and instruction in the <MCInst #885 MOVr <MCOperand Reg:R11>
3. Some preparation for OpaquePointer migration, replace call Type::getPointerElementType() - Now work in progress (not worked only 2 tests from all)

**Comment by bharadwajy** [comment]
Thanks for these changes! It would be good to ensure future changes continue to pass to clang-tidy / clang-format tests. Would you be able to look into adding a GitHub Action as a push pre-hook to ensure your good work here does not get undone by future changes?

**Comment by sv99** [comment]
clang-tidy warning a can see in my IDE. I don't like pre-hooks.

**Comment by bharadwajy** [comment]
> clang-tidy warning a can see in my IDE. I don't like pre-hooks.

A push pre-check is the only way (as far as I know) to ensure the conventions continue to be used - whether one likes them or not. Otherwise they will end up being undone. Happy to hear about other ideas you might have.

**Comment by sv99** [comment]
Now you code have mixed convention. llvm-project code now is being unified sequentially.

**Review by bharadwajy — APPROVED** [review]
OK. This is a good start.

**Comment by sv99** [comment]
Merging?? I have next PR for var renaming in the ARM subsystem

**Pull request merged**
