### PR TITLE
move instruction map to cpp file

### PR DESCRIPTION
**Pull request by Trass3r**
Fixes the bad compile times, at least for incremental builds.

### CODE REVIEW

**Comment by bharadwajy** [comment]
Thanks for submitting the changes.

Can you please add a brief description about the improvements/fixes this PR brings to the current tip of the project? Additionally, do you notice improved compile times on Linux or Windows or both?

**Comment by Trass3r** [comment]
Now the map just needs to be compiled once instead of for every file.
8f1dd52 further forces it to generate the map data at compile-time, which still costs quite a lot but saves much time in code generation, esp. for msvc.

**Comment by aaronsm** [comment]
Nice. What do your build times look like? A clean debug build for me of mctoll on a 6core MacMini is 8mins with Xcode.

**Comment by Trass3r** [comment]
Takes a while but heavily depends on the compiler and settings. Much time is wasted in the frontend on Windows because no PCH/modules are available.
Rebuilding just X86Raiser and llvm-mctoll in Release mode takes a minute with msvc and 4 cores.

**Comment by bharadwajy** [comment]
Thanks! Pushed changes to master as a single squashed commit.

**Pull request closed without merging**
