### PR TITLE
Added support to CMOVS condition.

### PR DESCRIPTION
**Pull request by rcorcs**
The cmovs conditional move if sign check the state of SF.
If SF=1 then condition is satisfied, otherwise it will be skipped.
https://wiki.cheatengine.org/index.php?title=Assembler:Commands:CMOVS

### CODE REVIEW

**Comment by bharadwajy** [comment]
Thanks for your PR. LGTM.

Would you be able to add a test case that exercises the new code before I pull it up the master?

Bharadwaj

**Comment by rcorcs** [comment]
Sure. I'm trying to build the programs in MiBench, where I found this missing instruction. I'll try to create a test case based on this program from MiBench.

**Comment by rcorcs** [comment]
Hi, I finally had some time for working on this. I have added an example that tests this patch. It is a snippet of code extracted from the MiBench/adpcm_c benchmark, which contains a cmovs x86 instruction when compiled with clang. Without this patch, llvm-mctoll is unable to raise it.

**Comment by bharadwajy** [comment]
Thanks for providing the test. I squashed both your commits to 1 commit and pushed.

**Pull request closed without merging**
