### PR TITLE
[X86-64] Add support for basic FP operations

### PR DESCRIPTION
**Pull request by martin-fink**
This adds support for the following instructions:
- `addss`, `addsd` (*)
- `subss`, `subsd` (*)
- `mulss`, `mulsd` (*)
- `divss`, `divsd` (*)
- `minss`, `minsd` (*)
- `maxss`, `maxsd` (*)
- `xorps`, `xorpd`, `pxor` (**)
- `andps`, `andpd`, `pand` (**)
- `orps`, `orpd`, `por` (**)

(*) Both register-register and register-memory operands are supported
```s
addsd xmm0, xmm1
addsd xmm0, qword ptr [rax]
```

(**) Only register-register operands are supported

If a xor instruction is done on one register to zero it out, we
recognize that and just set the register value to zero.

### CODE REVIEW

**Comment by bharadwajy** [comment]
Thanks for the PR.
 
> Do you think it would be better to recognize xor instructions that just zero-out a register (e.g. `xorpd xmm0, xmm0`) and
> generate more efficient code for that case?

I think that would be a good idea - similar to the way`xor` with same operands is handled.

**Comment by martin-fink** [comment]
Ok, I've changed it to match the implementation of integer `xor` operations, and also added a test case.

**Comment by rcorcs** [comment]
When recompiling the raised x86 binary from the fp-mem-ops.c test case down to ARM, all 'double' based operations are broken. See the output below:

1.5 + 0.5 = 2.0
1.5 + 0.5 = 0.0
1.5 - 0.5 = 1.0
1.5 - 0.5 = 0.0
1.5 * 0.5 = 0.75
1.5 * 0.5 = 0.00
1.5 / 0.5 = 3.0
1.5 / 0.5 = 0.0
1.5 == 0.5 = 0
1.5 == 0.5 = 0
1.5 == 1.5 = 1
1.5 == 1.5 = 1

It would be interesting if we could raise it to a target-independent LLVM bitcode.

**Comment by martin-fink** [comment]
Interesting. I tried cross-compiling the generated llvm code on my mac to arm and run it on a Raspberry Pi. For me it is broken as well, but in a different way:

1.5 + 0.5 = 2.0
0.5 + 2.0 = 2.0
1.5 - 0.5 = 1.0
0.5 - 1.0 = 1.0
1.5 * 0.5 = 0.75
0.5 * 0.8 = 0.75
1.5 / 0.5 = 3.0
0.5 / 3.0 = 3.0

If I compile fp-ops-mem.c with -O1 or higher, the issue seems to be fixed. I suspect the problem might not be the FP operations, but the argument passing (since on my machine the results look good).

I’ll look into it and try to find the underlying issue.

**Comment by martin-fink** [comment]
I've managed to fix the issues when compiling to ARM and tested my changes on a RaspberryPi. I think the changes are ready for review. If you want any commits squashed, please let me know.

**Comment by bharadwajy** [comment]
> I've managed to fix the issues when compiling to ARM and tested my changes on a RaspberryPi. I think the changes are ready for review. If you want any commits squashed, please let me know.

That's great! Thanks for quickly addressing the issue @rcorcs pointed out with ARM version of raised binaries. Thanks @rcorcs  for the help! I haven't yet gotten a chance to try it out myself.

Yes, please squash the commits to one or more (as needed) - with each commit pulling together related changes (and associated test(s)). That would certainly help with commit history.

**Comment by bharadwajy** [comment]
Thanks @martin-fink. Sorry for the delay.

I tested this branch, but see the output mismatch between failure on my Ubuntu 20.04. Here is the failure I see.

```
// CHECK: 1.5 == 0.5 = 1
          ^
<stdin>:10:15: note: scanning from here
1.5 == 0.5 = 0
              ^
<stdin>:11:1: note: possible intended match here
1.5 == 1.5 = 1
^

Input file: <stdin>
Check file: /mnt/datadrive/bharadwaj/github/src/public-mctoll/llvm-mctoll/test/smoke_test/fp-mem-ops.c

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            .
            .
            .
            5: 1.5 * 0.5 = 0.75 
            6: 1.5 * 0.5 = 0.75 
            7: 1.5 / 0.5 = 3.0 
            8: 1.5 / 0.5 = 3.0 
            9: 1.5 == 0.5 = 0 
           10: 1.5 == 0.5 = 0 
check:16'0                   X error: no match found
           11: 1.5 == 1.5 = 1 
check:16'0     ~~~~~~~~~~~~~~~
check:16'1     ?               possible intended match
           12: 1.5 == 1.5 = 1 
check:16'0     ~~~~~~~~~~~~~~~
>>>>>>
```

I'll look closer later today, but if you have a chance please take a look.

Thanks again for this patch. Much appreciated.

**Comment by martin-fink** [comment]
No worries! Thanks for your time to review my changes!

Sorry, that one was on me. The expected output for FileCheck was incorrect. Of course, we expect `1.5 == 1.5` to be `1`, not `0`. I've amended the commit.

**Comment by bharadwajy** [comment]
@martin-fink This PR adds/enables support for several opcodes but have no corresponding tests that exercise the added/enabled support (see list at the end of this comment). Would you consider moving the support for such opcodes out of these commits into a future separate PR with appropriate tests added? This will help very much in making progress on reviewing this PR and eventually pulling it to master?

Also, would you consider reorganizing the commits in this PR to one or more self-contained commits each encapsulating support to raise new (related) opcodes **and** tests to verify the added support? A single squashed-commit encompassing all 4 commits might be a last resort, if that seems too cumbersome.

List of opcodes without tests:
```
X86::ADDSDrm
X86::ADDSDrr
X86::ADDSDrr_Int
X86::ADDSSrm
X86::ADDSSrr
X86::ADDSSrr_Int
X86::CMPSDrm
X86::CMPSDrr
X86::CMPSSrm
X86::CMPSSrr
X86::DIVSDrm
X86::DIVSDrr
X86::DIVSDrr_Int
X86::DIVSSrm
X86::DIVSSrr
X86::DIVSSrr_Int
X86::MAXSDrm
X86::MAXSDrr
X86::MAXSSrm
X86::MAXSSrr
X86::MINSDrm
X86::MINSDrr
X86::MINSSrm
X86::MINSSrr
X86::MOVAPDmr
X86::MOVAPDrm
X86::MOVAPSmr
X86::MOVAPSrm
X86::MOVDI2SSrr
X86::MULSDrm
X86::MULSDrr
X86::MULSDrr_Int
X86::MULSSrm
X86::MULSSrr
X86::MULSSrr_Int
X86::PANDrr
X86::PORrr
X86::PXORrr
X86::SUBSDrm
X86::SUBSDrr
X86::SUBSDrr_Int
X86::SUBSSrm
X86::SUBSSrr
X86::SUBSSrr_Int
X86::UCOMISDrm_Int
X86::UCOMISDrr_Int
X86::UCOMISSrm_Int
X86::UCOMISSrr
X86::UCOMISSrr_Int
```

Thanks for this contribution, once again!

**Comment by martin-fink** [comment]
I've tried splitting them into self-contained commits, although I've combined some instructions into one PR (e.g ADDSD, SUBSD, ... or UCOMISD, CMPSD). Let me know if I should move some commits into a separate PR or if I should split the commits further.

I have also removed the instructions without tests (e.g. `ADDSDrr`) and added missing tests where neccessary.

**Comment by bharadwajy** [comment]
Thanks! Pulled on to master.

**Pull request closed without merging**
