### PR TITLE
support shared libs configuration

### PR DESCRIPTION
**Pull request by sv99**
Extracted common raiser files in the Raiser library and support for shared library configuration.

### CODE REVIEW

**Comment by bharadwajy** [comment]
Thanks for your interest in the project and the  PR.  I'm interested in learning more about motivation for and intended use of this change? 

Is the intent to encapsulate the raising functionality of `llvm-mctoll` as a shared library that can in turn  be used in  other (LLVM-based) tools?

**Comment by sv99** [comment]
I plan to use it for raising single function in the IDA Pro decompiller or in the Ghidra.

**Comment by bharadwajy** [comment]
> I plan to use it for raising single function in the IDA Pro decompiller or in the Ghidra.

Can you point to the  shared library built  as a result of these  changes that  you plan to use for this purpose?

**Comment by sv99** [comment]
I build LLVM with -DBUILD_SHARED_LIBS=ON for reduce used disk space.
Now the method of use has not yet been definitively determined.
I am exploring different variants.

**Comment by bharadwajy** [comment]
Can you change `CMakeLists.txt` to prefix all libraries built from this repo to be prefixed with `mctoll`? For e.g., the  library `libRaiser.so` currently generated would be renamed as `libmctollRaiser.so`, `libX66Raiser.so` would be renamed `libmctollX86Raiser.so` etc. This will be in keeping with the apparent convention followed during creation of LLVM and clang libraries.

**Comment by sv99** [comment]
libs renamed

**Review by bharadwajy — APPROVED** [review]

**Comment by sv99** [comment]
What I need to do?

**Comment by bharadwajy** [comment]
> What I need to do?



> What I need to do?

Look at information in the section "Merging is blocked" of [the current](#175) PR and the link provided therein and follow the suggested procedure.

**Comment by sv99** [comment]
sign this...

**Pull request merged**
